---
- name: Install required system packages.
  community.general.pacman:
    name:
      - openssh
    update_cache: true
    state: present

- name: Remove Node-RED AUR package.
  community.general.pacman:
    name:
      - nodejs-node-red
    state: absent
